language: php
php:
  - 5.3
  - 5.4

env:
  - DB=mysql

matrix:
  allow_failures:
    - env: DB=pgsql
  exclude:
    - php: 5.4
      env: DB=sqlite

before_script:
  - if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS phpbbblog_tests;' -U postgres; fi
  - if [ '$DB' = 'pgsql' ]; then psql -c 'create database phpbbblog_tests;' -U postgres; fi
  - if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS phpbbblog_tests;'; fi
  - pyrus install phpunit/DbUnit
  - phpenv rehash
  - git submodule update --init

script:
  - phpunit --configuration tests/travis/$DB.travis.xml

notifications:
  email:
    recipients:
      - m@michaelcullum.com
      - erikfrerejean@phpbb.com
    on_success: always
    on_failure: always
 
  irc:
    channels:
      - "irc.freenode.org#unknownbliss"
    on_success: always
    on_failure: always

